INSERT INTO paket_soals(nama, jenis_tryout,  created_at) VALUES
    ('Try Out Nasional 1',2, now());


INSERT INTO soal_tius(id, paket_id, soal, pilihan_1, pilihan_2, pilihan_3, pilihan_4, jawaban, pembahasan, skor) VALUES
    (1,1,'OPAS =','MADU.','SAPU.','PESURUH.','RAJA.','RACUN.','Sinonim OPAS = RACUN.',5),
    (2,1,'LESAP =','LAJU .','HISAP.','CEPAT.','MASUK.','LENYAP.','Sinonim LESAP = LENYAP.',5),
    (3,1,'FAKULTATIF ><','JURUSAN.','MATA KULIAH.','PILIHAN.','TIDAK WAJIB.','WAJIB.','Antonim FAKULTATIF >< WAJIB.',5),
    (4,1,'EPIGON  ><','AMATIR.','TUNGGAL.','POLIGON.','JAMAK.','PROFESIONAL.','Antonim EPIGON >< PROFESIONAL.',5),
    (5,1,'VADEMIKUM  ><','DAFTAR PUSTAKA.','DAFTAR ISI.','BIOGRAFI.','BIBLIOGRAFI.','KAMUS BESAR.','Antonim VADEMIKUM >< KAMUS BESAR.',5),
    (6,1,'KIPAS ANGIN : GERAK : LISTRIK = ...','LISTRIK : CAHAYA : TV','LISTRIK: SUARA : RADIO.','MESIN : LISTRIK : SUARA.','LAMPU : PANAS : LISTRIK.','SETRIKA : PANAS : LISTRIK.','KIPAS ANGIN : GERAK : LISTRIK = SETRIKA : PANAS : LISTRIK.',5),
    (7,1,'BERLARI : KERINGAT = ...','NANGIS : SEDIH.','SEDIH : NANGIS.','DARAH : LUKA.','SENYUM : TERTAWA.','LUKA : DARAH.','BERLARI : KERINGAT = LUKA : DARAH.',5),
    (8,1,'VENUS : TATASURYA = ...','ENGLISH : NUMBER.','TIDAK DAPAT DITARIK KESIMPULAN.','DELAPAN : ANGKA.','BUMI : PLUTO.','DWI : SANSKERTA.','VENUS : TATASURYA = DWI : SANSKERTA.',5),
    (9,1,'KERETA API : GAMBIR = PESAWAT : …','BELAWAN.','TANJUNG PRIUK.','LEBAK BULUS.','BAKAUHENI.','NGURAH RAI.','KERETA API : GAMBIR = PESAWAT: NGURAH RAI.',5),
    (10,1,'BACAAN UNTUK PERTANYAAN NO 40 S.D. 42

Perlu dijelaskan bahwa sebagai aparatus komunikasi, bahasa memiliki rupa-rupa keterbatasan dan ketidaksempurnaan. Banyak kekuaranglengkapan yang melekat erat (inheren) di dalam sosok bahasa itu sendiri, yang pada gilirannya justru dapat mencuatkan aneka kesalahpahaman. Sebab pertama dari kekuranglengkapan dan kekurangsempurnaan bahasa adalah ihwal penandaan atau penyimbolan unsur-unsur kebahasaan. Penandaan komponen-komponen bahasa tersebut lazimnya dilakukan baik secara konvensional maupun inkonvensional.
Penyimbolan secara konvensional dilaksanakan atas dasar kesepahaman dan kesepakatan bersama di antara sesama warga pemakaian bahasa dalam sebuah masyarakat bahasa. Karena dasar utamanya adalah kesepakatan atau konvensi, maka lazimnya hasik penyimbolan yang demikian itu tidak banyak menghadirkan persoalan. Ambillah contoh kata jawa segawon yang dalam bahasa Indonesia anjing dan dalam bahasa Inggris dog. Penamaan terhadap sosok binatang piaraan yang buas, berbulu bagus, tidak terlalu besar, dan sukanya meraung-raung keras itu dilakukan secara konvensional. Karena simbol tersebut muncul dalam kesepakatan atau kesepahaman bersama, tidak ditemukan persoalan pemakaian unsur kebahasaan tersebut di dalam praktik komunikasi.
Penyimbolan yang kedua dilakukan secara arbitrer. Artinya, satuan lingual tertentu digunakan untuk menyimboli sesuatau entitas di alam raya ini secara semena-mena dan tidak selalu jelas alasan dan justifikasinya. Karena itu, simbolisasi yang demikian rentan terhadap aneka kesamaran dan ketaksaan. Sejumlah pakar bahkan dengan tegas menyebutkan, kesamaran dan ketaksaan tersebut sesungguhnya merupakan sifat kebahasaan yang melekat sebagai akibat yang tidak terhindarkan lagi dari simbolisasi arbtrer itu.

Masalah utama yang dibicarakan dalam paragraf pertama pada teks di atas adalah…','Penyimbolan yang kedua dilakukan secara arrbitrer.','Kekuranglengkapan di dalam sosok bahasa dapat mencuatkan kesalahpahaman.','Penyebab kekuranglengkapan dan kekurang-sempurnaan bahasa.','Penandaan unsur-unsur kebahasaan dilakukan baik secara konvensional maupun inkonvensional.','Bahasa memiliki rupa-rupa keterbatasan dan ketidaksempurnaan.','Bahasa memiliki rupa-rupa keterbatasan dan ketidaksempurnaan.',5),
    (11,1,'Jika kata arbitrer diartikan sebagai semena-mena maka makna kata arbiter adalah…','Orang yang sering melakukan pekerjaan sesuka hatinya.','Orang yang dipercaya untuk menjadi penengah atau pemutus antara dua belah pihak yang sedang bersengketa.','Orang tidak mempedulikan apapun.','Orang yang pekerjaanya menjadi perantara perdagangan antara penjual dan pembeli.','Orang yang sering mengartikan suatu kata sesuka hatinya.','Orang yang sering mengartikan suatu kata sesuka hatinya.',5),
    (12,1,'Kesimpulan dari teks di atas adalah…','Kesamaran dan ketaksaan di dalam sosok bahasa adalah suatu keniscayaan.','Kesamaran dan ketaksaan di dalam sosok bahasa merupakan hal yang bisa dihindari.','Sejumlah pakar bahkan dengan tegas menyebutkan, kesamaran dan ketaksaan tersebut sesungguhnya merupakan sifat kebahasaan.','Kesamaran dan ketaksaan di dalam sosok bahasa bisa memunculkan aneka kesalahpahaman.','Kesamaran dan ketaksaan di dalam sosok bahasa terjadi sebagai akibat simbolisasi.','Kesamaran dan ketaksaan di dalam sosok bahasa terjadi sebagai akibat simbolisasi.',5),
    (13,1,'Semua pakaian musim dingin berbulu.
Sebagian pakaian yang berbulu harganya mahal. 
Sebagian pakaian yang mahal tidak mudah rusak.
','Semua pakaian yang murah bukan pakaian musim dingin.','Semua pakaian musim dingin harganya murah.','Semua pakaian berbulu bukan pakaian musim dingin.','Semua pakaian musim dingin tidak mudah rusak.','Sebagian pakaian musim dingin mudah rusak.','Kesimpulan yang paling sesuai dengan hukum silogisme adalah “Sebagian pakaian musim dingin mudah rusak”.',5),
    (14,1,'Semua atlet pandai melompat dan atlet yang pandai melompat gemar berenang.
Atlet yang gemar berenang, tidak pandai memasak.','Atlet yang tidak pandai memasak, tidak pandai melompat.','Atlet yang tidak pandai memasak, gemar berenang dan tidak pandai melompat.','Atlet yang tidak pandai memasak, pandai melompat.','Atlet yang tidak pandai memasak, tidak pandai melompat dan tidak gemar berenang.','Tidak ada atlet yang pandai memasak.','Kesimpulan yang paling sesuai dengan hukum silogisme adalah “Tidak ada atlet yang pandai memasak”.',5),
    (15,1,'Setiap siswa di kelas X memiliki kalkulator grafik.
Setiap orang yang memiliki kalkulator grafik mengerti tentang fungsi trigonometri.
Roni adalah siswa kelas X.','Roni tidak memiliki kalkulator grafik.','Roni mengerti tentang fungsi trigonometri tetapi tidak memiliki kalkulator.','Roni belum tentu memiliki kalkulator grafik.','Roni belum tentu mengerti tentang fungsi trigonometri.','Roni mengerti tentang funsi trigonometri.','Kesimpulan yang paling sesuai dengan hukum silogisme adalah “Roni mengerti tentang funsi trigonometri.”.',5),
    (16,1,'Rata-rata sekelompok bilangan adalah 40. Ada bilangan yang sebenarnya 60 tetapi terbaca 30. Setelah dihitung kembali ternyata rata-rata yang benar adalah 41. Banyak bilangan dalam kelompok itu adalah….','25','45','35','40','30','40=  x/n (1)dan 41=  (x+30)/n  (2)
Sehingga diperoleh persamaan sbb:
40n = x ( dari persamaan 1)
41n = x+30 ( dari persamaan 2)
41 n = 40 n + 30
n = 30',5),
    (17,1,'Chris membeli sepatu futsal seharga Rp1juta. Dua bulan kemudian sepatu tersebut dijual dengan keuntungan 40%. Namun saat Chris hendak pulang ke rumah, 2 lembar uang seratus ribu dan 1 lembar uang lima puluh ribu hilang di jalan. Berapa persen keuntungan Chris jika dihitung berdasarkan kas yang ada saat ini?','0.35','0.2','0.25','0.3','0.15','Uang milik chris = 1.400.000 – 250.000 = 1.150.000
Keuntungan = 150.000/1.000.000  x 100%=15%',5),
    (18,1,'Jika 5 ekor kambing dapat melahap 5 lapangan rumput dalam waktu 5 hari, maka 500 ekor kambing dapat melahap 500 lapangan rumput dalam waktu … hari.','Tidak dapat ditentukan','50','500','5000','5','Cukup jelas, menggunakan perbandingan terbalik.',5),
    (19,1,'Sebuah tangki yang berisi air mengalami kebocoran pada bagian dasarnya. Apabila debit air keluar adalah 200mL/detik dan kondisi tangki saat itu hanya terisi ¼ bagian sehingga air dalam tangki tersebut dapat habis dalam waktu 6 menit. Berapakah volume tangki itu?','120 L','72 L','215 L','200 L','288 L','1/4 V=200mL x 360=72000mL=72 L
V=72 x 4=288L',5),
    (20,1,'Tiga bilangan membentuk suatu deret geometri. Jika hasil kali ketiganya adalah 216 dan hasil jumlah ketiganya adalah 26 maka rasio deret tersebut adalah….','NAS005','NAS 002','NAS003','NAS004','NAS001','NAS006',5),
    (21,1,'Seorang murid diminta mengerjakan 8 dari 10 soal. Soal dengan no 1 s.d. 5 harus dikerjakan. Banyaknya pilihan soal yang dikerjakan adalah…','3','5','6','8','10','NAS007',5),
    (22,1,'Jay memiliki 100 ekor ayam yang terdiri dari 70 ekor ayam jantan yang 58 di antaranya sudah siap potong. Jika jumlah ayam yang siap potong ada 72 ekor, banyak ayam betina yang belum siap potong adalah…ekor.','18','17','14','15','16','v  Dari 100 ekor ayam, 70 ekor adalah ayam jantan. Maka jumlah ayam betina adalah 100-70=30 ekor
v  Dari 72 ayam siap potong, 58 ekor adalah ayam jantan.
v  Maka jumlah ayam betina siap potong adalah 72-58= 14 ekor.
v  Jumlah ayam betina belum siap potong= 30-14= 16 ekor.',5),
    (23,1,'Andi, Bobi, dan Charlie membagi 100 apel. Andi menerima 15 lebih banyak daripada yang diterima Bobi, 25 lebih sedikit daripada yang diterima Charlie. Banyaknya apel yang diterima Charlie adalah…buah.','45','74','60','63','55','Misalkan A= Andi, B= Bobi, & C= Charlie.
Soal tsb dpt kita ubah ke dlm bentuk persamaan matematika sbb:
B= A-15
C= A+25
A+B+C=100
Jumlah seluruh apel adalah 100 buah, maka
A+(A-15)+(A+25)=100
3A+10=100
A=30
Jadi, jumlah apel yg dimiliki Charlie adalah
C=30+25= 55 buah',5),
    (24,1,'Chris dan teman-temannya bermain catur. Setiap anak akan bermain satu kali dengan temannya. Jika jumlah anak yang bermain sebanyak 17 orang. Berapa kali mereka bermain?','34','382','342','361','136','NAS008',5),
    (25,1,'KETERANGAN UNTUK PERTANYAAN NO 55 S.D. 57

Suatu proyek terdiri dari beberapa jenis proyek kecil, yakni proyek A, B, C, D, E dan F. Proyek kecil ini berkaitan satu sama lain sehingga tiap jenis pekerjaan diatur sebagai berikut:
v  Proyek B hanya boleh dikerjakan bersama proyek C
v  Proyek A boleh dikerjakan bersama proyek E
v  Proyek B tidak boleh dikerjakan bersama dengan proyek D
v  Proyek E dikerjakan jika dan hanya jika proyek F dikerjakan

31.   Jika proyek A dan D dikerjakan maka yang pasti tidak dikerjakan adalah proyek ...','tidak ada','C','E','F','B','B tidak boleh sama D.',5),
    (26,1,'Jika minggu kedua pekerjaan wajib mengerjakan proyek F dan tidak boleh mengerjakan proyek C maka ...','Pekerjaan juga tidak mengerjakan proyek D','Pekerjaan pasti mengerjakan proyek C','Pekerjaan tidak mengerjakan proyek E','Pekerjaan pasti mengerjakan proyek A','Pekerjaan tidak mengerjakan proyek B','B hanya jika C, berarti jika C tidak, B tidak.',5),
    (27,1,'Jika pekerjaan sudah mengerjakan proyek E maka ...','Pekerjaan tidak akan mengerjakan proyek A','Pekerjaan tidak mengerjakan proyek D','Pekerjaan akan mengerjakan proyek E','Pekerjaan hanya akan mengerjakan proyek B','Pekerjaan juga mengerjakan proyek F','E hanya jika F.',5),
    (28,1,'1, 2, 2, 4, 8, 32, ...','64','128','1024','512','256','1x2 = 2
2x2 = 4
2x4 = 8
4x8 = 32
32x8 = 256',5),
    (29,1,'22, 66, 33, 34, 30, 90, 45, 46, 42, … , …','66, 128','23, 76','98, 346','280, 249','126, 63','Bilangn dikali 3, bagi 2, tambah 1 kurang 4. Diulangi.',5),
    (30,1,'81, 9, 12, 36, 33, 66, 64, 8, 11, … , …','14, 28','12, 28','12, 22','13, 28','33, 30','Mulai dari 81 s.d. 66 polanya adalah akar, tambah 3, kali 3, kurang 3 kali 2. Diulang lagi mulai dari 64.',5),
    (31,1,'F, H, J, L, N, …','O, P','P, Q','T, U','Q, S','P, R','Mulai dari F, polanya lompat 2 huruf setelahnya.',5),
    (32,1,'NAS009','NAS010','NAS011','NAS014','NAS013','NAS012','Apabila dirangkai menjadi kubus, hanya gambar C yang sesuai dengan kerangka kubusnya.',5),
    (33,1,'NAS015','NAS016','NAS017','NAS018','NAS020','NAS019','Setiap lingkaran memiliki pasangan identik, meskipun diputar.',5),
    (34,1,'NAS021','NAS022','NAS023','NAS026','NAS025','NAS024','Kiri atas, samping kanan atas, sebelah kiri bawah, dan kiri bawah ditransfer ke bangun akhir.',5),
    (35,1,'NAS027','NAS028','NAS029','NAS030','NAS032','NAS031','Apabila dirotasi gambar yang identik dengan gambar tersebut adalah gambar D.',5);

    
    
INSERT INTO soal_twks(id, paket_id, soal, pilihan_1, pilihan_2, pilihan_3, pilihan_4, jawaban, pembahasan, skor) VALUES
    (1,1,'Seena adalah generasi milenial yang tidak bisa terlepas dari gawai. Seena sangat aktif sekali di media sosial, namun sayangnya pada masa menjelang Pemilu 2019, Seena sangat sering membagikan informasi tanpa terlebih dahulu memperhatikan kebenarannya, hal ini tentunya sangat membencikan bagi orang-orang yang menerima berita hoax dimaksud. Sikap Seena ini harus kita hindari, karena hal ini sangat bertentangan dengan Pancasila, khususnya...','Sila Pertama','Sila Kedua','Sila Keempat','Sila Kelima','Sila Ketiga','Berita hoax merupakan salah satu hal yang sangat bertentangan dengan Sila Ketiga, karena hal tersebut dapat memecah belah persatuan dan kesatuan NKRI',5),
    (2,1,'Aurita adalah seorang ASN pada Kementerian Keuangan, sejak tahun 2014 Aurita ditempatkan pada instansi yang memiliki unit vertikal di beberapa daerah. Namun dimanapun Aurita ditempatkan, Aurita selalu dapat beradaptasi dengan daerah dimaksud. Hal ini karena Aurita memiliki sifat yang baik terutama dia selalu mencintai sesama manusia, tenggang rasa dan tepa selira. Serta tidak semena-mena terhadap orang lain. Sifat Aurita ini adalah cerminan Pancasila, terutama...','Sila Pertama','Sila Ketiga','Sila Keempat','Sila Kelima','Sila Kedua','Penekanan dalam wacana di atas adalah sifat selalu mencintai sesama manusia, tenggang rasa dan tepa selira. Serta tidak semena-mena terhadap orang lain, hal ini sejalan dengan Pancasila Sila Kedua.',5),
    (3,1,'Pada tahun 2019 Badan Usaha Milik Desa (BUMDes) Sukatentrem memiliki kinerja keuangan yang jauh lebih baik dibandingkan dengan tahun-tahun sebelumnya. Setelah ditelusuri lebih lanjut, peningkatan kinerja ini disebabkan adanya perubahan skema kerja pada BUMDes Sukatentrem, sejak ditunjuknya Pak Tito sebagai Kepala BUMDes, Pak Tito selalu mendorong semua pegawainya untuk bekerja saling membantu dan gotong royong dengan pegawai lain, walaupun terkadang hal tersebut tidak berkaitan dengan tugas dan fungsi pegawai dimaksud. Hal tersebut sesuai dengan nilai-nilai Pancasila, khususnya....','Sila Pertama','Sila Kedua','Sila Ketiga','Sila Keempat','Sila Kelima','Dalam bacaan di atas ditekankan adanya sikap mendorong semua pegawainya untuk bekerja saling membantu dan gotong royong dengan pegawai lain, hal ini sejalan dengan Pancasila Sila Kelima..',5),
    (4,1,'Di bawah ini adalah Butir-Butir Pancasila Sila Ketiga, kecuali...','Mengembangkan rasa cinta kepada tanah air dan bangsa. ','Memelihara ketertiban dunia yang berdasarkan kemerdekaan, perdamaian abadi dan keadilan sosial. ','Mengembangkan persatuan Indonesia atas dasar Bhinneka Tunggal Ika. ','Memajukan pergaulan demi persatuan dan kesatuan bangsa.','Mengembangkan rasa kebanggaan kepada daerah kelahiran. ','Kebanggaan kepada daerah kelahiran bukanlah sikap yang mencerminkan Sila Ketiga.',5),
    (5,1,'Melalui berbagai kebijakan dan program pemerintah, Indeks Pembangunan Manusia (IPM) telah mengalami peningkatan, semula pada tahun 2015 sebesar 69,5 menjadi 71,39 pada tahun 2018. Capaian tersebut termasuk dalam standar High Human Development versi lembaga internasional. Capaian ini tentunya tidak luput dari implementasi mandatory spending bidang pendidikan sebesar 20% dari Anggaran Pendapatan dan Belanja Negara (APBN) selama satu dekade terakhir. Adanya mandatory spending sektor pendidikan ini merupakan amanah dari...','Pasal 31 ayat (1) UUD 1945.','Pasal 31 ayat (2) UUD 1945.','Pasal 31 ayat (3) UUD 1945','Pasal 31 ayat (5) UUD 1945.','Pasal 31 ayat (4) UUD 1945','Dalam Pasal 31 ayat (4) UUD 1945 menyatakan bahwa negara memprioritaskan anggaran pendidikan sekurang-kurangnya dua puluh persen dari anggaran pendapatan dan belanja negara serta dari anggaran pendapatan dan belanja daerah untuk memenuhi kebutuhan penyelenggaraan pendidikan nasional.',5),
    (6,1,'Rancangan Kitab Undang-Undang Hukum Pidana (RKUHP) memperoleh banyak sekali masukan dari berbagai elemen masyarakat, diantaranya adalah masukan dari Direktur Pusat Pengkajian Pancasila dan Konstitusi (Puskapsi) Fakultas Hukum Universitas Jember, yang menyebut bahwa Pasal 432 RKUHP tidak sejalan  dengan UUD 1945, seperti diketahui bersama bahwa Pasal 432 RKUHP menyatakan setiap orang yang bergelandangan di jalan atau di tempat umum yang mengganggu ketertiban umum akan mendapatkan sanksi paling banyak Rp1.000.000,00. Hal tersebut kurang sejalan dengan UUD 1945 khususnya...','Pasal 32 ayat (1) UUD 1945.','Pasal 32 ayat (2) UUD 1945.','Pasal 33 ayat (1) UUD 1945.','Pasal 33 ayat (2) UUD 1945.','Pasal 34 ayat (1) UUD 1945.','Dalam Pasal 34 ayat (1) UUD 1945 menyatakan bahwa fakir miskin dan anak-anak terlantar dipelihara oleh negara.',5),
    (7,1,'Pada tanggal 17 Septeber 2019, Rancangan Undang-Undang tentang Sumber Daya Air (RUU Sumber Daya Air) disahkan Dewan Perwakilan Rakyat lewat rapat paripurna. RUU Sumber Daya Air ini telah menjadi Program Legislasi Nasional Dewan Perwakilan Rakyat pada 2018. Semangat RUU Sumber Daya Air memang Dewan Perwakilan Rakyat dan Pemerintah ingin sejalan air nantinya benar-benar dapat menyejahterakan rakyat atau publik. Upaya yang dilakukan Dewan Perwakilan Rakyat dan Pemerintah tersebut sejalan dengan...','Pasal 32 ayat (1) UUD 1945.','Pasal 32 ayat (2) UUD 1945.','Pasal 33 ayat (2) UUD 1945.','Pasal 34 ayat (1) UUD 1945.','Pasal 33 ayat (3) UUD 1945.','Dalam Pasal 33 ayat (3) UUD 1945 menyatakan bahwa bumi dan air dan kekayaan alam yang terkandung di dalamnya dikuasai oleh negara dan dipergunakan untuk sebesar-besar kemakmuran rakyat.',5),
    (8,1,'Sebagai bangsa yang majemuk maka dalam kehidupan di masyarakat kita harus saling menghormati dan bertoleransi tinggi. Sebab apabila egois atau memaksakan kehendak pribadi atau golongan akan dapat menimbulkan ...','Kekacauan dalam masyarakat.','Rusaknya kemajemukan bangsa.','Putusnya tali persaudaraan.','Putusnya harapan masyarakat.','Menimbulkan konflik komunal.','Sebagai bangsa yang majemuk maka dalam kehidupan di masyarakat kita harus saling menghormati dan bertoleransi tinggi. Sebab apabila egois atau memaksakan kehendak pribadi atau golongan akan dapat menimbulkan disintegrasi konflik komunal (konflik kedaerahan).',5),
    (9,1,'Presiden dengan bantuan DPR menyatakan perang, membuat perdamaian dan perjanjian dengan negara lain. Hal ini tercantum dalam UUD 1945 pasal ...','Pasal 9 UUD 1945.','Pasal 14 UUD 1945.','Pasal 18 UUD 1945.','Pasal 12 UUD 1945.','Pasal 11 UUD 1945.','Pasal 11 UUD 1945 ayat (1) menyatakan presiden dengan bantuan DPR menyatakan perang, membuat perdamaian dan perjanjian dengan negara lain.',5),
    (10,1,'Angka pengangguran di Indonesia masih sangat tinggi. Salah satu bentuk usaha mengurangi untuk angka pengangguran adalah ...','Memperbaiki sektor industri.','Memperluas pendidikan.','Memanfaatkan semberdaya alam.','Meminta bantuan luar negeri.','Memperluas kesempatan kerja.','Salah satu bantuk usaha mengurangi angka pengangguran adalah memperluas kesempatan kerja, peningkatan mutu SDM dengan pendidikan dan menciptakan lapangan kerja baru.',5),
    (11,1,'Dalam sistem pertahanan dan keamanan negara dinyatakan bahwa TNI sebagai kekuatan pertahanan negara, sedangkan Polri sebagai kekuatan dengan fungsi ','Sosial kemasyarakatan.','Menjaga hukum dan keadilan.','Pengendalian umum.','Penyeledikan dan keamanan publik.','Keamanan dan ketertiban masyarakat.','Dalam sistem pertahanan dan keamanan negara Indonesia dinyatakan bahwa TNI sebagai kekuatan pertahanan negara, sedangkan Polri sebagai kekuatan dengan fungsi keamanan dan ketertiban masyarakat (pasal 30 ayat 3 dan 4).',5),
    (12,1,'Sebagai warga negara kita mempunyai hak dan kewajiban yang sama. Di bawah ini yang termasuk salah satu bentuk hak, kecuali ...','Kebebasan dalam berserikat, berkumpul dan mengeluarkan pendapat.','Memeluk agama serta menjalankan ibadah sesuai dengan keyakinannya.','Membentuk keluarga dan melanjutkan keturunan melalui perkawinan yang sah.','Mendapat pekerjaan serta kehidupan yang layak.','Membayar pajak sesuai yang telah ditentukan.','Sebagai warga negara kita mempunyai hak dan kewajiban yang sama. Kewajiban yang sama merupakan membayar pajak karena pajak setiap warga negara wajib membayar sesuai yang telah ditentukan undang-undang.',5),
    (13,1,'Relevansi, kualitas, dan efisiensi pelatihan kerja perlu ditingkatkan untuk ...','Perlindungan dan pengembangan lembaga tenaga kerja','Pengembangan budaya usaha masyarakat.','Perluasan dan pengembangan kesempatan kerja.','Pengembangan sistem jaminan sosial.','Peningkatan kualitas dan produktivitas tenaga kerja.','Relevansi, kualitas, dan efisiensi pelatihan kerja perlu ditingkatkan guna peningkatan kualitas dan produktifitas tenaga kerja. Hal ini sangat penting karena erat hubungannya dengan hasil dalam proses produksi dalam suatu spesialisasi pekerjaan.',5),
    (14,1,'Sumber Daya Alam baik yang dapat diperbaharui maupun tidak dapat diperbaharui perlu dikelola dengan baik hal itu ditujukan untuk pencegahan ...','Efektifitas pengolahan, konservasi, dan rehabilitasi sumber daya alam dan lingkungan hidup.','Kelembagaan dan hukum pengolahan sumber daya alam dan pelestarian lingkungan.','Masyarakat dalam pengolahan sumber daya alam dan pelestarian lingkungan hidup.','Akses informasi sumber daya alam dan lingkungan hidup.','Kerusakan dan pencemaran lingkungan hidup yang akan terjadi di sekitar.','Pengelohan sumber daya alam yang baik guna mencegah kerusakan dan pencemaran lingkungan hidup yang akan terjadi, pengolahan sumber daya alam yang baik misalnya dapat mencegah banjir dan tanah longsor akibat penebangan hutan sembarangan atau mencegah pencemaran air akibat penggunaan sabun detergen dalam kehidupan sehari-hari.',5),
    (15,1,'Perjuangan bangsa Indonesia melawan penjajah didorong karena adanya faktor dari luar dan dalam negeri. Penyebab utama dari dalam negeri adalah sebagai berikut, kecuali ...','Peranan bahasa melayu sebagai bahasa kesatuan.','Sebagian bangsa Indonesia bergama Islam.','Kesadaran bangsa Indonesia akan harga dirinya sebagai bangsa merdeka.','Timbul kaum cerdik pandai akibat politik etis.','Pengaruh pergerakan kebangsaan Filipina.','Pengaruh pergerakan kebangsaan Filipina.',5),
    (16,1,'Dari tinjauan historis, kelahiran Orde Baru merupakan upaya pemerintah menegakkan pemerintah yang bersifat ...','Feodal militerisme.','Diktator militerisme.','Demokratis pancasilais.','Sosialistis.','Feodal oligarkis.','Dari tinjauan historis, kelahiran Orde Baru merupakan upaya pemerintah menegakkan pemerintahan yang bersifat Feodal oligarkis.',5),
    (17,1,'Pembangunan secara bertahap merupakan program jangka panjang pemerintah Indonesia pada masa Orde Baru. Namun, adanya unsur-unsur korupsi, kolusi, dan nepotisme menyebabkab hanya sekelompok orang yang mendapat fasilitas untuk menikmati hasil pembanguan tersebut. Keadaan ini berakibat buruk bagi kehidupan masyarakat pada umumnya, salah satunya adalah ...','Semakin tingginya angka pengangguran di Indonesia.','Harga barang tidak terkendali karena dipegang kelompok tertentu.','Pembangunan yang dilakukan tidak sesuai dengan kebutuhan','Penggusuran rumah rumah warga sering dilakukan dengan dalih pembangunan.','Kesenjangan sosial antara golongan kaya dan miskin senakin lebar.','Pembangunan secara bertahap merupakan program jangka panjang pemerintah Indonesia pada masa Orde Baru. Namun, adanya unsur-unsur korupsi, kolusi, dan nepotisme menyebabkan hanya sekelompok orang yang mendapat fasilitas untuk menikmati hasil pembangunan tersebut. Keadaan ini berakibat buruk bagi kehidupan masyarakat pada umumnya, salah satunya adalah kesenjangan sosial antara golongan kaya dan miskin semakin lebar yang sampai saat ini masih terjadi.',5),
    (18,1,'Penggunaan jasa satelit komunikasi seperti Satelit Palapa yang dimiliki Indonesia sangat penting dan merupakan suatu keharusan karena ...','Memudahkan penduduk untuk berkomunikasi.','Merupakan sumber devisa terbesar negara Indonesia.','Indonesia harus mengatasi ketertinggalan dari bangsa lain.','Jumlah penduduk Indonesia sangat banyak.','Wilayah Indonesia merupakan wilayah kepulauan yang sangat luas.','Penggunaan jasa satelit komunikasi domestik seperti satelit Palapa yang dimiliki Indonesia sangat penting dan merupakan suatu keharusan karena wilayah Indonesia merupakan kepulauan yang sangat luas.',5),
    (19,1,'Perjuangan Serikat Islam merupakan pergerakan ...','Dagang.','Sosial.','Nasional.','Pendidikan.','Agama.','Perjuangan Sarekat Islam merupakan pergerakan Agama.',5),
    (20,1,'Buku “Habis Gelap Terbitlah Terang” berisi kumpulan surat ...','Douwes Decker.','Multatuli.','Cut Nyak Dien.','Dewi Sartika.','R.A. Kartini.','Buku Habis Gelap Terbitlah Terang berisi kumpulan surat R.A kartini yang mana diterbitkan setelah beliau meninggal.',5),
    (21,1,'Pada akhir pendudukan Jepang timbul pertentangan antara golongan tua dan golongan muda tentang konsepsi dalam mencapai kemerdekaan nasional. Golongan tua antara lain seperti tersebut di bawah ini, kecuali ...','Soekarno','Tan Malaka.','Mr. Maramis.','Mr Subardjo.','Adam Malik.','Golongan tua antara lain kecuai kecuali Adam Malik.',5),
    (22,1,'Organisasi induk olahraga senam seluruh Indonesia adalah ','Perseri.','Pertina.','Perpani.','PASI.','Persani.','Organisasi induk yang menaungi olehraga senam di Indonesia adalah Persatuan Senam Indonesia, atau biasa disingkat Persani.',5),
    (23,1,'Thomas Matulesi adalah nama asli pahlawan ...','I Gusti Ngurah Rai.','Ki Hajar Dewantara.','Ahmad Dahlan.','Tuanku Imam Bonjol.','Kapitan Pattimura.','Dilahirkan di Ambon pada tanggal 8 Juni 1783, Thomas Matulessi melawan Belanda bersama pejuang-pejuang Maluku lainnya dan rakyat Maluku. Pada tangal 14 Mei 1817, seluruh rakyat Saparua menyatakan kesetiaan dan dukungan mereka serta mengangkat Thomas Matulessi menjadi Kapitan Pattimura.',5),
    (24,1,'Penghargaan yang diberikan kepada perorangan atau kelompok atas jasa-jasanya dalam melestarikan lingkungan hidup di Indonesia adalah ...','Adipura.','FFI.','Satya Wacana.','Satya bumi.','Kalpataru','Penghargaan Kalpataru adalah suatu penghargaan yang diberikan kepada perotangan atau kelompok atas jasa-jasanya dalam melestarikan lingkungan hidup di Indonesia.',5),
    (25,1,'ILO adalah organisasi di bawah naungan PBB yang mengurusi masalah ...','Pangan.','Pengungsi.','Pendidikan.','Kesehatan.','Buruh.','ILO (International Labour Organisation) adalah sebuah organisasi di bawah PBB yang menampung isu-isu buruh internasional.',5),
    (26,1,'Salah satu tujuan ASEAN adalah memelihara kerja sama yang erat dan bermanfaat dengan organisasi-organisasi internasional dan regional lain yang ...','Memberikan bantuan teknik pelatihan kepada ASEAN.','Dapat membentuk program-program ASEAN.','Sama tujuannya dengan tujuan ASEAN.','Berdekatan dengan kawasan ASEAN.','Dapat diajak dialog oleh ASEAN.','Salah satu tujuan ASEAN adalah memelihara kerja sama yang erat dan bermanfaat dengan organisasi-organisasi internasional dan regional lain yang dapat diajak dialog oleh ASEAN.',5),
    (27,1,'Berikut ini sebab-sebab perjanjian internasional; baik secara bilateral maupun multilateral dapat berakhir, kecuali ...','Para peserta setuju untuk mengakhiri perjanjian.','Perundingan (negotiation) tidak dihadiri kepala negara.','Telah tercapainya tujuan perjanjian.','Habis masa berlakunya.','Salah satu pihak peserta perjanjian punah.','Sebab-sebab perjanjian internasional baik secara bilateral maupun multilateral dapat berakhir, kecuali salah satu pihak perjanjian punah..',5),
    (28,1,'Apakah Saudara telah mendengarkan keputusan pimpinan perusahaan?
Penggunaan kata “saudara” pada kalimat di atas terjadi perubahan makna. Perubahan makna apakah kata tersebut?','Amelioratif.','Peyoratif.','Menyempit.','Sinestesia.','Meluas.','a. Amerlioratif adalah perubahan makna buruk menjadi lebuh baik
b. Peyoratif adalah perubahan makna baik menjadi lebih buruk
c. Meluas adalah perubahan makna dari satu makna menjadi beberapa makna
d. Menyempit adalah perubahan makna dari beberapa makna menjadi satu makna saja
e. Sinestesia adalah perubahan dua makna karena pertukaran tanggapan dari kedua indra yang berbeda.
',5),
    (29,1,'Kalimat majemuk yang tepat di bawah ini adalah ...','Adi tidak mau minum obat.','Pertunjukan sirkus dihadiri orang tua atau anak-anak.','Walaupun kaya, tapi ia juga congkak.','Dia bekerja keras daripada melamun.','Ia pandai melukis tetapi ayahnya melarangnya','Kalimat majemuk adalah kalimat yang terbentuk daru dua klausa atau lebih yang dihubungkan dengan kata penghubung yang sesuai. Kalimat majemuk yang tepat adalah “Ia pandai melukis tetapi ayahnya melarangnya.”',5),
    (30,1,'Bella belajar menari balet di Sanggar Tari Merak.
Kalimat berikut ini memiliki pola serupa dengan kalimat di atas adalah ...','Barang haram itu dikirim bandar ke daerah-daerah terpencil.','Wina takut melihat harimau mengaum.','Aku kapok berbisnis dengan penjudi seperti kamu.','Ayah melarang kami bergaul dengan pemabuk.','Adik minum obat batuk agar sembuh.','Bella   belajar menari   balet   di sanggar Tari Merak.
  S               P                 O               Keterangan

Kalimat yang berpola sama SPOK adalah:

Adik   minum   obat batuk   agar sembuh.
  S          P              O            Keterangan.     
',5);


INSERT INTO soal_tkps(id, paket_id, soal, pilihan_1, pilihan_2, pilihan_3, pilihan_4, pilihan_5, pembahasan, skor_1, skor_2, skor_3, skor_4, skor_5) VALUES
    (1,1,'Untuk mempertahankan prestasi dalam sebuah kompetisi. Maka yang harus dilakukan adalah...','Mempelajari teknik-teknik baru untuk persiapan kompetisi tahun depan.','Berlatih secara rutin dan terpogram.','Manambah latihan fisik untuk meningkatkan daya tahan tubuh.','Mempelajari kelemahan tim lawan untuk dapat mengalahkan mereka.','Melakukan pertandingan uji coba meningkatkan kemampuan kami.','Topik Kemampuan Mengkoordinir Orang Lain, karena terdapat kata kunci yang berkaitan dengan peran kita sebagai pemimpin. Untuk jawaban, carilah yang mencerminkan ketegasan kita memberi komando/tugas kepada rekan, teman, atau anggota tim. Tindakan yang diberikan harus jelas dan tegas.',5,4,3,1,2),
    (2,1,'Tim kerja dimana anda berperan sebagai ketua tim mengalami penurunan produktivitas kerja, maka hal yang akan anda lakukan untuk menanggulangi keadaan tersebut adalah...','Segera merombak tim kerja sebagai bentuk evaluasi performance kinerja.',' Memecat karyawan yang terbukti mengalami penurunan kinerja.','Menganggap penurunan produktivitas sebagai hal yang lumrah.','Memperhatikan kondisi fisik dan psikologi karyawan.','Menghilangkan tunjangan kerajinan pada karyawan yang terbukti mengalami penurunan kinerja.','Topik Kemampuan Mengkoordinir Orang Lain, karena terdapat kata kunci yang berkaitan dengan peran kita sebagai pemimpin. Untuk jawaban, carilah yang mencerminkan ketegasan kita memberi komando/tugas kepada rekan, teman, atau anggota tim. Tindakan yang diberikan harus jelas dan tegas.',5,1,3,4,2),
    (3,1,'Sebagai ketua dalam pentas seni anda mendapat laporan bahwa bintang tamu acara tersebut mengundurkan diri 1 hari sebelum hari H, anda bingung karena tiket terjual habis. Agar acara tersebut terselenggara dengan baik, yang akan anda lakukan adalah...','Memberikan bayaran lebih kepada artis tersebut.','Mengganti bintang tamu dengan artis lain yang memiliki kepopuleran yang lebih.','Memundurkan jadwal pentas seni hingga bintang tamu tersebut mau tampil.','Mendatangi bintang tamu tersebut dan memintanya untuk bersikap professional.','Mengembalikan ganti rugi tiket pada para calon penonton.','Topik Kemampuan Mengkoordinir Orang Lain, karena terdapat kata kunci yang berkaitan dengan peran kita sebagai pemimpin. Untuk jawaban, carilah yang mencerminkan ketegasan kita memberi komando/tugas kepada rekan, teman, atau anggota tim. Tindakan yang diberikan harus jelas dan tegas.',3,4,2,5,1),
    (4,1,'Kalau saya membeli hadiah untuk teman, sebelum membeli saya akan mempertimbangkan …','Uang yang saya miliki.','Kemampuan saya dan kesenangan teman saya.','Uang saya dan sedikit kesenangan teman saya.','Mengesampingkan keuangan saya.','Lebih dalam pertimbangkan kesenangan teman saya.','Topik Orientasi Kepada Orang Lain, karena terdapat kata kunci yang berkaitan dengan kemungkinan kita membantu orang lain. Untuk jawaban, carilah yang mencerminkan kepedulian terhadap sesama, hindari kegiatan/tindakan yang menguntungkan kita.',1,4,2,3,5),
    (5,1,'Saya senang jika rekan saya dalam satu tim bisa menjadi rekan kerja yang...','Mandiri.','Dapat bekerja sama.','Profesional.','Jujur.','Penuh dedikasi.','Topik Profesionalitas, karena terdapat kata kunci yang berkaitan dengan adanya suatu pilihan antara pekerjaan dengan kehidupan non-pekerjaan atau adanya kebutuhan kita untuk meningkatkan kualitas bekerja. Untuk jawaban, carilah yang mencerminkan sikap kita untuk komitmen terhadap pekerjaan dan terus bekerja lebih baik.',2,5,4,1,3),
    (6,1,'Ada yang mengatakan bahwa tidak semua orang yang berpendidikan tinggi mendapatkan pekerjaan sehingga banyak anak-anak yang tidak termotivasi untuk menerima pendidikan tinggi. Maka Anda akan...','Tetap ingin memiliki pendidikan yang tinggi.','Mengurungkan niat untuk memperoleh pendidikan tinggi.','Biasa saja.','Menganggapnya sebatas isu saja.','Bekerja saja.','Topik Kemampuan Bekerja Sama Dalam Kelompok, karena terdapat kata kunci peran kita dalam tim (bukan ketua kelompok), carilah yang mencerminkan sikap kita untuk bekerja sama dalam tim. Hindari pilihan kegiatan yang bersifat egois.',5,1,4,3,2),
    (7,1,'Apa yang anda lakukan sebagai anggota biasa dalam suatu unit untuk mengambil keputusan disaat pimpinan tidak ada...','Tetap menunggu pimpinan unit untuk datang.','Meminta rekan lain saja yang mengambil keputusan.','Bagaimanapun juga, saya tidak bersedia mengambil keputusan.','Saya akan mengambil keputusan untuk menyelamatkan kondisi rumit.','Saya menelpon dulu pimpinan lalu mengambil keputusan.','Topik Profesionalitas, karena terdapat kata kunci yang berkaitan dengan adanya suatu pilihan antara pekerjaan dengan kehidupan non-pekerjaan atau adanya kebutuhan kita untuk meningkatkan kualitas bekerja. Untuk jawaban, carilah yang mencerminkan sikap kita untuk komitmen terhadap pekerjaan dan terus bekerja lebih baik.',1,2,3,4,5),
    (8,1,'Suatu hari anda akan mengadakan audit kesebuah sekolah yang lokasinya cukup jauh dan hanya bisa ditempuh dengan perjalanan darat. Ditengah perjalanan mobil yang anda bawah mengalami kecelakaan padahal mobil tersebut adalah mobil pinjaman. Untuk memperbaiki mobil tersebut anda harus mengeluarkan uang sangat banyak. Setelah mobil di servis setelah menunggu 3 jam, anda kembali melanjutkan perjalanan. Ketika akan pulang kepala sekolah memberikan sejumlah uang, sikap kamu...','Menerima uang transport tersebut jika tidak diketahui oleh rekan tim yang lainnya.','Mengembalikan uang transport secara tegas dan halus.','Menolak karena kamu tahu itu bentuk gratifikasi.','Menolak karena disuruh atasan untuk bekerja dengan jujur dan bebas KKN.','Marah karena kepala sekolah telah berusaha untuk menyogok.','Topik Integritas Diri, Terdapat kata kunci janji, maka atas hal-hal berkaitan dengan komitmen (keterlambatan). Untuk jawaban terkait integritas, carilah yang mencerminkan kepedulian terhadap sifat jujur,peduli akan janji dan sikap anti korupsi.',1,4,5,3,2),
    (9,1,'Kita hidup di negara yang memiliki ragam kepercayaan, budaya dan adat istiadat yang berbeda-beda. Di perusahaan anda sendiri terdiri dari orang orang yang berbeda latarbelakang, banyak karyawan muslim yang mengeluhkan sulitnya beribadah karena ketersediaan tempat atau pada jam untuk beribadah mereka harus tetap bekerja, sikap anda...','Akan memfasilitasi tempat untuk beribadah mereka di lingkungan perusahaan.','Mendiskusikan hal ini dengan jajaran pimpinan dan pemilik perusahaan untuk dicari solusinya.','Karena pemilik perusahaan seorang non muslim, maka itu sudah menjadi aturan yang harus dipatuhi karyawan.','Memberikan kebijakan yang bersifat toleran kepada karyawan.','Bersifat toleran dan menyediakan semua fasilitas ibadah karyawan.','Topik Sosial dan Budaya, karena terdapat kata kunci yang berkaitan dengan budaya ketimuran Indonesia. Untuk jawaban, carilah yang mencerminkan sikap kita sesuai dengan norma kesusilaan yang berlaku.',3,5,1,2,4),
    (10,1,'Anda akan ditugaskan oleh atasan anda untuk menjadi panitia pameran yang akan memperkenalkan produk produk perusahaan, termasuk menjual beberapa produk untuk melihat respon pembeli. Pameran tersebut akan diikuti oleh banyak perusahaan yang juga memperkenalkan produk meraka ada yang setipe dengan anda dan ada juga yang berbeda, untuk menarik pengunjung apa yang anda lakukan...','Memperagakan produk yang berkualitas di estalase agar banyak yang tertarik.','Membuat pengunjung nyaman dengan stand anda dengan menyediakan tempat duduk dll.','Selalu bersikap ramah terhadap pengunjung yang lewat dan mempersilakan untuk mampir.','Membuat konsep stand pameran yang menarik.','Membuat stand pameran yang besar agar semua pengunjung bisa muat di stand anda.','Topik Kreativitas dan Inovasi, karena terdapat kata kunci suatu penciptaan hal baru dalam kehidupan ataupun pekerjaan, carilah yang mencerminkan sikap kita untuk terbuka atas hal baru, inovatif dan out of the box.',2,3,4,5,1),
    (11,1,'Anda merupakan seorang manajer pada sebuah perusahaan. Sudah beberapa bulan ini ada salah satu karyawan yang tidak dapat bekerja dengan baik, bahkan cendrung menghambat aktivitas diperusahaan, banyak pekerjaan yang tertunda karena harus menunggu dia menyelesaikan pekerjaannya, terkadang setelah ditunggu pun hasilnya sangat buruk, padahal anda sudah memastikan bahwa beban kerja karyawan tersebut sudah sesuai dengan peraturan dan prosedur perusahaan. Perusahaan pun telah memberikan kesempatan beberapa kali untuk perbaikan dan memberi pelatihan, namun setelah diamati tidak ada perubahan sama sekali, yang anda lakukan...','Memberi kesempatan terus sampai dia bisa berubah menunjukkan peforma terbaiknya, meski akan mengganggu kinerja perusahaan.','Memberikan kesempatan karena setiap karyawan berhak atas hal tersebut.','Terpaksa mencari penggantinya agar kinerja perusahaan kembali membaik.','Memberhentikannya dan memastikan semua keputusan saya terdokumentasi.','Memberhentikan karyawan yang bermasalah tersebut, karena tidak bekerja dengan baik.','Topik kemampuan menggerakkan dan mengkoordinir orang lain, sebagai atasan kita harus mampu mengkoordinir bawahan, memberikan kesempatan untuk perbaikan dan pelatihan namun jika tidak ada perubahan maka seorang atasan harus tegas, karena atasan juga punya tanggung jawab terhadap kemajuan perusahaan yang dikelolahnya.',1,2,3,5,4),
    (12,1,'Di divisi tempat anda bekerja sedang terjadi sebuah masalah yang dapat mempengaruhi kinerja karyawan dalam menyelesaikan tugasnya. Anda sebagai atasan sudah mencoba untuk berfikir dan memandang masalah tersebut secarah objektif dan menganalisis setiap karyawan yang dapat terpengaruh atas masalah tersebut, kemudian yang anda lakukan...','Meminta mereka untuk berpartisipasi lebih baik lagi dan patuh terhadap semua kebijakan yang akan di ambil.','Menyuruh mereka mematuhi semua kebijakan dan meminta penyelesaian dari masalah tersebut.','Meminta masukkan dari mereka dan membuat keputusan secepatnya agar dipatuhi semua karyawan divisi.','Membuat keputusan secepatnya dan memberitahu karyawan divisi akan hal tersebut, agar tidak kaget.','Meminta masukan dari mereka, melakukan revisi seperlunya, dan kemudian mengajak mereka turut mengimplementasikan rencana yang telah disepakati bersama.','Topik kemampuan menggerakkan dan mengkoordinir orang lain, sebagai atasan harus melibatkan bawahan tetapi keputusan tetap ada di tangan kita, memberikan pemahaman dan bagian dari kelompok kita harus saling terbuka, saling bertanggung jawab dan memiliki kesadaran serta selalu mengkomunikasikan setiap ada permasalahan.',3,1,4,2,5),
    (13,1,'Anda diminta atasan anda untuk menyelesaikan sebuah masalah di dalam pekerjaan karena atasan anda menilai anda karyawan yang paling mampu mengatasinya dengan baik dan efektif. Namun ketika di tengah jalan penyelesaian yang anda berikan terhadap permasalahan tersebut sedikit kurang optimal untuk memberikan solusi terbaik seperti yang diharapkan perusahaan, yang anda lakukan...','Saya akan merubah semua solusi yang ada dan membuat penyelesaian baru.','Saya meminta atasan untuk memberikan saya waktu lebih untuk memikirkannya.','Saya melakukan modifikasi atas keputusan tersebut, terkadang modifikasi kecil sudah cukup.','Mengembalikan tugas tersebut kepada atasan untuk di limpahkan kapada karyawan lain.','Memikirkan cara  yang paling efektif dari penyelesaian sebelumnya.','Topik kreativitas dan inovasi, mampu memikirkan hal hal kreatif dan imajinatif untuk melakukan perbaikan pada sebuah proses sehingga mendapatkan hasil terbaik, tidak harus merubah tapi melakukan modifikasi sehingga apa yang menjadi tujuan dapat tercapai.',3,2,5,1,4),
    (14,1,'Beberapa hari terakhir ini di kantor anda sedang disibukkan dengan banyaknya deadline pekerjaan yang harus diselesaikan secepatnya, sehingga setiap komponen perusahaan diminta untuk memberikan kemampuan terbaiknya bagi perusahaan, karena jika ada pekerjaan yang tertunda akan berpengaruh terhadap produktivitas kerja. Namun ada beberapa karyawan yang datang kepada anda bercerita dan mengeluhkan beberapa hal yang tidak berkaitan dengan pekerjaan, sikap anda...','Saya selalu terbuka terhadap setiap karyawan untuk berkeluh kesah kapanpun mereka membutuhkannya.','Hal tersebut harus di batasi karena dapat mengganggu kinerja perusahaan.','Selalu bersimpati dan memberikan nasehat dan solusi yang paling baik terhadap setiap masalah mereka.','Bersimpati dan memberikan solusi dan nasehat dengan tetap memprioritaskan kepentingan perusahaan.','Saya akan selalu baik kepada setiap karyawan di perusahaan dan dapat menjadi teman curhat mereka setiap waktu.','Topik orientasi kepada orang lain, dengan menunjukkan etikad baik, empati dan kepedulian terhadap sesama, namun sesuai dengan kapasitas yang dimiliki dengan tetap memprioritaskan kepentingan perusahaan anda berbuat baik dan kerjaan tetap jalan.',2,3,4,5,1),
    (15,1,'Anda telah bekerja sesuai dengan SOP yang perusahaan berikan kepada setiap karyawan dengan jelas, sudah terdokumentasi sebagai panduan bagi setiap karyawan dalam bekerja dan telah menerapkannya setiap hari dengan baik, namun terkadang ada kondisi dimana sebuah masalah yang timbul tidak dijelaskan bahkan tidak ada di dalam SOP yang perusahaan berikan, yang akan anda lakukan...','Tetap mengikuti sop yang ada meskipun pekerjaan selesai jadi sangat lama dan mengganggu kinerja.','Meminta bantuan kepada rekan karyawan yang lain untuk dicarikan solusi terbaik.','Melihat dari kondisi yang ada dan saya sesuaikan dengan misi perusahaan agar pekerjaan cepat terselesaikan.','Menyuruh atasan untuk meriview kembali sop yang ada agar karyawan dapat bekerja dengan baik.','Memikirkan penyelesaian yang sekira cocok dan bisa saya kerjakan sesuai kemampuan saya dan misi perusahaan.','Topik kemampuan bekerja mandiri dan tuntas, menunjukkan sikap bertanggung jawab terhadap pekerjaan dengan tidak menyalahi tujuan perusahaan dan menyelesaikan pekerjaan secara cepat.',1,3,5,2,4),
    (16,1,'Anda baru saja di mutasi ke sebuah cabang baru dari perusahaan anda yang berlokasi diluar kota, anda diberikan tanggung jawab yang lebih besar dari sebelumnya untuk mengontrol dan mewujudkan tujuan perusahaan di kantor cabang baru tersebut, dan memajukan perusahaan. Namun cabang baru tersebut di isi oleh karyawan karyawan baru dari daerah dan belum berpengalaman, yang anda lakukan...','Memberitahukan kepada karyawan baru tersebut terkait pekerjaan yang harus mereka kerjakan.','Menyuruh mereka untuk lebih berinisiatif untuk mengimprovisasi diri dan meningkatkan kualitas dalam bekerja.','Menyuruh mereka membaca semua tugas mereka dan menerapkannya dalam setiap pekerjaan.','Meminta untuk bekerja maksimal dan loyal terhadap perusahaan.','Mengkomunikasikan sasaran perusahaan dan memotivasi staf saya untuk mencapainya.','Topik kemampuan menggerakkan dan mengkoordinir orang lain, menunjukkan sikap dan kemampuan memimpin dan menjadi katalisator yang dapat mempengaruhi orang lain, sebagai atasan kita harus mengkomunikasikan, memberitahu kepada bawahan tujuan perusahaan dan membimbing mereka terutama jika karyawan belum berpengalaman.',4,1,3,2,5),
    (17,1,'Beberapa tahun lagi anda akan memasuki usia pensiun dari salah satu instansi pemerintahan tempat anda bekerja selama ini. Tanggung jawab anda untuk mengabdi bagi negarapun telah selesai. Sekarang anda memasuki babak baru dimana tidak lagi terikat dengan pekerjaan dan pengabdian terhadap negara. Hal apa yang akan anda rencanakan untuk selanjutnya ketika waktu itu telah tiba...','Saya membuka usaha kecil-kecilan dirumah sambil menghabiskan hari tua saya dengan anak dan cucu-cucu saya.','Memiliki tanah di berbagai tempat strategis untuk investasi masa tua saya dan keluarga.','Membuka lapangan kerja buat orang terdekat dan yang membutuhkan pekerjaan karena zaman sekarang sulit mendapatkan pekerjaan.','Memiliki warisan harta yang berguna bagi anak dan cucu saya kelak ketika waktu tersebut sudah tiba.','Beristirahat saja setiap hari di rumah menikmati hari hari tua saya bersama keluarga.','Topik kemampuan bekerja berkelanjutan, mempunyai tekat untuk pengembangan diri dan berfikiran maju, selalu tidak pernah puas dengan apa yang sudah dicapai, tekad untuk sukses',5,3,4,2,1),
    (18,1,'Terdapat himbauan dan ajakan dari pemerintah kepada masyarakat terutama aparatur sipil negara untuk mengurangi pemanasan global akibat dari efek gas rumah kaca yang sudah terjadi hampir di seluruh belahan dunia, kontribusi yang dapat anda lakukan untuk mendukung program pemerintah tersebut sebagai seorang ASN yang setiap harinya berangkat untuk bekerja...','Menanami pekarangan rumah dengan pohon pohon hijau.','Menggunakan transpotasi umum untuk berpergian.','Mematikan peralatan listrik yang tidak penting.','Membuang sampah pada tempatnya.','Membatasi penggunaan limbah plastik dalam kegiatan sehari-hari.','Topik sosial budaya kesadaran akan hukum yang berlaku berupa tata tertib, himbauan, ajakan dan peraturan pemerintah untuk di dukung dan diterapkan.',1,5,4,2,3),
    (19,1,'Anda mendapatkan tugas untuk menyelesaikan urusan kantor diluar kota dengan beberapa rekan team lainnya. Karena tugas ini sangat penting bagi perusahaan, anda diminta untuk bekerja dengan cermat, cepat, efektif dan efisien dan selalu mematuhi SOP yang ada. Namun ada salah satu dari rekan anda yang melakukan kesalahan cukup fatal karena tidak bekerja sesuai dengan prosedur, yang anda lakukan...','Mendalami kesalahan yang telah diperbuat teman tersebut.','Memintanya untuk mempertanggung jawabkan kesalahannya kepada atasan.','Membicarakannya dengan rekan kerja yang lain untuk mengambil sikap.','Mengelurkannya dari team dan menyuruh bertanggung jawab.','Membicarakan kepada atasan tentang permasalahan tersebut.','Topik kemampuan bekerja sama dalam kelompok, selalu bersifat terbuka dan mengkomunikasikan setiap permasalahan dalam team untuk dibicarakan dan di carikan solusi terbaik bentuk dari tanggung jawab atas pekerjaan.',2,3,5,1,4),
    (20,1,'Anda sedang melakukan diskusi dengan rekan kerja divisi anda, kemudian ketika diskusi berlangsung ada seorang rekan kerja anda yang mengusulkan sebuah ide yang menurutnya sangat baik, namun menurut anda hal tersebut beresiko besar jika tetap dilakukan, ketika anda memberikan tanggapan namun teman tersebut tidak menanggapi dengan sikap yang baik, seakan-akan tidak mau gagasannya di sanggah,sikap anda...','Diam saja dan mengikuti semua gagasannya demi menghindari konflik.','Memintanya untuk memberikan gagasan yang lebih realistis dan resikonya kecil.','Mengajaknya untuk bicara santai dan fokus pada tujuan awal.','Memintanya untuk memikirkan kembali gagasan yang diusulkan.','Keluar dari ruang diskusi dan memberitahukan kepada atasan.','Topik kemampuan mengendalikan diri dari sebuah kondisi yang tidak terduga dan diinginkan dengan tetap berfikiran jernih penuh tanggung jawab, sabar dan selalu mempertimbangkan baik buruknya.',2,4,5,3,1),
    (21,1,'Anda baru saja di pindahkan ke departement lain di kantor anda yang masih memiliki hubungan dengan pekerjaan sebelumnya. Namun di tempat anda yang baru setiap karyawan sangat serius dalam bekerja, jarang bahkan tidak pernah anda melihat mereka bekerja dengan santai dan sedikit bercanda, sikap anda...','Tetap bekerja seperti biasanya pada saat anda bekerja di tempat lama.','Mempertanyakan tentang kondisi tersebut kepada rekan baru anda.','Melakukan pembiasaan dengan cara kerja ditempat baru.','Bekerja sesuai dengan jati diri saya sendiri tanpa terpengaruh orang lain.','Mengajak mereka untuk tidak terlalu serius dalam bekerja.','Topik kemampuan beradaptasi dengan lingkungan kerja baru agar dapat diterima dan menunjukkan sikap supel dan adaptif terhadap perubahan dan mampu menyesuaikan diri.',1,2,5,4,3),
    (22,1,'Team anda mendapat tugas dari atasan anda untuk membantunya menyeleseikan dokumen-dokumen penting yang harus dibawahnya dalam rapat petinggi perusahaan. Dokumen yang harus disiapkan cukup banyak. Namun salah seorang rekan anda sulit untuk diajak bekerjasama dan cendrung menganggap sepele tugas yang diberikan atasan, perilaku dan sikapnya bahkan dapat berbahaya bagi keselarasan di tempat kerja, sikap anda...','Meminta atasan untuk menegurnya agar bisa diajak bekerja sama.','Memberikan pengertian agar sadar akan tugas dan tanggung jawab.','Menyuruhnya untuk menyelesaikan tugasnya secepat mungkin.','Membiarkan saja, karena bukan urusan anda untuk menegurnya.','Memintanya untuk tidak menganggap sepele setiap pekerjaan.','Topik profesionalisme dalam bekerja, melaksanakan tugas dengan disiplin dan penuh tanggung jawab tehadap sebuah pekerjaan yang menjadi tanggung jawab.',2,5,3,1,4),
    (23,1,'Suatu hari Saya dan teman-teman bersepakat untuk pergi ke perpustakaan kota bersama guna mencari buku untuk mengerjakan tugas sekolah. Saya dan seorang teman Saya sudah menunggu selama 1 jam di tempat yang disepakati. Namun ada dari dua orang teman saya yang datang terlambat dan mengatakan bahwa mereka membantu seorang ibu ibu yang keserempet mobil dan si pengemudi mobil tersebut meninggalkannya begitu saja. Maka yang akan saya lakukan adalah...','Menyuruh mereka pulang saja karena sudah tidak bisa menepati janji dan menghargai waktu orang lain.','Menyuruh mereka untuk duduk dan menanyakan permasalahan yang terjadi dan kondisi mereka.','Memberitahu mereka bahwa lain kali mereka tidak akan ditunggu, jika tidak memberikan sama sekali.','Merasa kesel dan kecewa karena sudah menunggu lama dan menyuruh mereka pulang saja dan saya langsung ke perpustakaan.','Mengajak mereka ke perpustakaan kota untuk melupakan peristiwa yang baru saja terjadi.','Topik orientasi terhadap orang lain, kepedulian dan empati terhadap orang lain, tidak menganggap acuh setiap orang, memahami kondisi orang lain, teman yang sedang terkena musibah.',1,5,3,2,4),
    (24,1,'Ketika menjadi panitia sebuah acara di kampus anda, anda mendapatkan telpon dari pacar anda bahwa dia membutuhkan bantuan anda untuk menjemputnya ke stasiun kota, pacar anda mengatakan jika sudah mencoba menghubungi jasa angkutan online tapi tidak ada yang mengambil orderannya, sedangkan tugas anda masih banyak dan harus selesei hari ini juga mengingat acara akan dilaksanakan besok harinya, sikap anda...','Minta maaf dan mengatakan bahwa anda tidak bisa datang untuk menjemputnya.','Memintanya untuk mencoba lagi untuk memesan jasa kendraan online.','Menjemputnya terlebih dahulu dan melanjutkan pekerjaan yang tertunda selama anda pergi.','Meminta rekan anda yang lain untuk menyelesaikan tugas anda dan pergi menjemput pacar anda.','Tidak datang menjemput dan resiko diputusin pacar oleh pacar anda.','Topik profesionalisme dalam bekerja, kita dituntut untuk lebih mementingkan kepentingan pekerjaan dan tanggung jawab terhadap pekerjaan ketika anda hal lain yang menghalanginya dan fokus pada pekerjaan.

',4,5,3,2,1),
    (25,1,'Weekend ini anda berencana membantu adik anda dan teman kelompoknya untuk membuat sebuah artikel ilmiah. Ketika sedang mengajarkan bagaimana cara membuat sebuah karya ilmiah yang baik, kemudian ditelevisi terdapat berita tentang semakin besarnya angka pengangguran di indonesia, yang dapat anda sarankan untuk adik dan dan teman kelompoknya...','Minta mereka untuk kuliah dengan sungguh sungguh agar pada saat lulus nanti mudah mendapatkan pekerjaan.','Meminta rajin dan serius ketika kuliah dan patuh pada aturan agar bisa lulus tepat waktu.','Meminta mereka menyiapan soft skill dan hard skill mulai dari sekarang.','Meminta mereka untuk tidak hanya menjadi kutu buku saja tapi juga ikut organisasi.','Tidak menyarankan apa apa berharap mereka sadar sendiri nantinya tentang persaingan dunia kerja.','Topik semangat berprestasi selalu meningkatkan kemampuan untuk pengembangan diri dan bekerja keras yang berguna untuk masa depan yang lebih unggul, dengan menyeimbangkan soft skill dan hard skill.',3,2,5,4,1),
    (26,1,'Anda diminta atasan anda untuk membantunya weekend ini di kantor menyelesaikan beberapa tugas penting. Namun dalam perjalanan menuju ke kantor, kendaraan yang anda tumpangi tiba-tiba rusak sehingga harus diperbaiki terlebih dahulu, dan membutuhkan waktu beberapa menit agar bisa digunakan lagi, sedangkan atasan anda telah menelpon berulang kali meminta anda segera datang ke kantor karena dia sangat membutuhkan bantuan anda...','Berusaha secepatnya ke kantor dengan mencoba untuk berjalan kaki.','Menunggu kendraan sampai selesai diperbaiki dan meminta atasan menunggu.','Meminta bantuan atasan di kantor agar segera dijemput dilokasi kerusakan kendraan yang anda tumpangi.','Berjalan kaki sambil berusaha mencari tumpangan untuk ke kantor.','Meminta pengemudi kendraan yang anda tumpangi untuk memperbaiki kendraannya dengan cepat.','Topik kreativitas dan inovasi, mencari jalan lain dan solusi terhadap permasalahan yang ada,, berusaha untuk datang secepatnya memenuhi tanggung jawab membantu atasan anda secepatkan mungkin dan mengambil inisatif agar dapat membantu sesegera mungkin.',4,3,1,5,2),
    (27,1,'Di perusahaan tempat anda bekerja saat ini memiliki tingkat disiplin dan aturan yang cukup ketat dimana setiap karyawan diminta untuk mampu bekerja cepat dan menyelesaikan semua tugas dan pekerjaan dengan baik, anda merupakan seorang karyawan baru yang tentu saja belum terlalu terbiasa akan hal tersebut, dalam melakukan semua pekerjaan anda di kantor hal apa yang anda lakukan...','Lebih suka jika bekerja dengan suasana kelompok dan bisa saling bertukar pikiran.','Lebih Suka bekerja sendiri dan fokus untuk menyelesaikan pekerjaan yang diemban.','Melibatkan teman-teman dalam setiap hal hal kecil terkait pekerjaan yang ada.','Tekun, teliti, dan bekerja sampai semua pekerjaan dapat cepat diselesaikan.','Lebih suka pekerjaan yang memberikan saya kebebasan waktu yang lebih fleksibel.','Topik kemampuan bekerja mandiri dan tuntas, dapat bekerja dengan cepat, disiplin sesuai prosedur dengan fokus dan cepat dan benar menyelesaikan pekerjaan sebaik mungkin dan penuh tanggung jawab. ',4,2,3,5,1),
    (28,1,'Anda termasuk ke dalam salah satu dari 3 kandidat karyawan terbaik yang akan dipromosikan untuk naik jabatan di perusahaan anda. Untuk memutuskan siapa yang layak diantara kandidat yang ada, pimpinan perusahaan memberikan tugas yang sebelumnya tidak pernah anda kerjakan, bagaimana anda mengatasinya...','Bekerja sama dengan dua kandidat yang lain untuk saling membantu.','Membaca berbagai referensi yang mendukung penyelesaian tugas tersebut.','Membeli buku buku penunjang di gramedia untuk memudahkan dalam pemahaman terhadap tugas.','Mencari referensi di google dan jurnal jurnal online dan memakainya untuk penyelesaian tugas agar hasilnya maksimal.','Meminta bantuan dan pencerahan kepada atasan untuk menjelaskan bagaimana cara mengerjakannya.','Topik kemampuan belajar berkelanjutan, gemar membaca dan terus menimbah ilmu, berfikiran maju dan punya tekad untuk berkembang dan suka tantangan.',2,5,3,4,1),
    (29,1,'Bulan ini anda menerima berbagai macam keluhan dari pelanggan anda terkait pelayanan dari perusahaan terhadap mereka. Sebagai perusahaan yang memberikan layanan anda sudah sepatutnya mengerti akan kebutuhan pelanggan agar mereka tetap menggunakan jasa perusahaan anda, ketika ada seorang pelanggan yang datang menyampaikan keluhannya, yang anda lakukan...','Meminta pelanggan tersebut untuk menyampaikan keluhannya.','Menanyakan keluhan pelanggan tersebut dan menjadikan bagian dari solusi.','Mendengarkan setiap keluhan yang masuk kepada anda dengan seksama.','Mengatasi keluhan yang masuk dengan tetap tenang dan fokus.','Mencoba mengerti keluhan pelanggan terhadap perusahaan.','Topik orientasi terhadap pelayanan, memberikan pelayanan terbaik, dan optimal dan cepat kepada pelanggan dan serta menyelesaikan keluhan mereka dengan solusi yang terbaik.',2,5,3,4,1),
    (30,1,'Rekan team kerja anda dimarahi oleh atasan pada saat mengumpulkan tugas team karena sudah telat beberapa menit mengumpulkan tugasnya. Hal ini disebabkan karena rekan anda tersebut harus menyusun pekerjaan tersebut terlebih dahulu sebelum dikumpulkan ditambah lagi semua rekan anggota team mengumpulkan tugas pribadi mereka juga terlambat, sehingga rekan anda yang bertugas untuk mengasembbly setiap pekerjaan jadi tidak menyelesaikan pekerjaannya tepat waktu, sikap anda...','Mendengarkan saja rekan anda dimarahi setelah itu memberikan semangat untuk tidak dimasukkan kehati ucapan atasan.','Minta maaf kepada teman karena keterlambatan juga disebabkan oleh anggota team yang lain.','Mengakui kesalahan kepada atasan jika anda juga turut berkontribusi pada masalah tersebut.','Mengakui kesalahan kepada teman dan berjanji tidak akan mengulanginya lagi.','Mengajak rekan anda untuk membicarakannya dan menghiburnya rekan yang dimarahi atasan.','Topik Integritas diri, mampu bertanggung jawab atas setiap tindakan yang diperbuat, berlaku jujur dan mengakui kesalahan bentuk dari kesadaran diri dan komitment terhadap peraturan.',1,3,5,4,2),
    (31,1,'Beberapa minggu yang lalu atasan anda pernah memberitahu anda bahwa dia mempunyai jadwal untuk bisa menandatangani kontrak dengan beberapa orang klien baru dalam beberapa minggu ke depan untuk pengembangan perusahaan, namun tampaknya atasan anda lupa akan hal tersebut karena terlalu sibuk mengurusi banyak hal dan sering tidak berada dikantor karena pergi ke luar kota, sebagai seorang asisten yang akan anda lakukan adalah...','Mengingatkan atasan bahwa punya rencana untuk bertemu klien.','Membuat rencana pertemuan dan memberitahu atasan untuk disetujui.','Membuat rencana pertemuan dengan klien atasan dan memberitahukannya.','Memberitahu atasan bahwa dia harus bertemu klien untuk urusan bisnis dalam waktu dekat.','Menunggu atasan membicarakannya lagi, lalu baru melakukan persiapan pertemuan.','Topik kreativitas dan inovasi, mampu berfikiran imajinatif terhadap sebuah permasalahan dan berinisiatif untuk melakukan suatu pekerjaan dengan tetap sesuai sop dan persetujuan.',3,5,4,2,1),
    (32,1,'Dosen anda meminta anda untuk ikut dalam sebuah perlombaan yang dalam waktu dekat akan diselenggarakan oleh universitas tempat anda berkuliah. Dosen anda melihat bahwa anda memiliki talenta sesuai dengan diskripsi dari perlombaan, akan tetapi anda tidak menyadarinya, sikap anda...','Berterimakasih kepada Dosen tersebut karena telah memuji anda sebagai seseorang yang bertalenta.','Menerima dan mengembangkan lebih dalam talenta yang anda miliki.','Bersedia mengikuti perlombaan tersebut dan meminta bantuan dosen untuk membantu dan membimbing anda.','Bersedia asalkan dosen anda selalu mau memberikan bimbingan jika nanti menemui permasalahan.','Menerima dan mengikuti perlombaan tersebut sebisanya.','Topik semangat berprestasi, selalu berusaha meningkatkan kemampuan dan mengembangkan diri, kerja keras dan semangat kompetisi.',2,5,4,3,1),
    (33,1,'Hampir setiap minggu anda selalu menjalankan dinas ke luar kota. Pekerjaan anda menuntut anda untuk selalu mempersiapkan segala kebutuhan yang diperlukan ketika bertugas, mulai darang barang barang pribadi sampai ke dokumen penting yang harus dibawah. Kendala yang sering terjadi adalah anda agak sedikit pelupa, terkadang barang bawaan anda bisa tertinggal, belum lagi resiko kerusakan selama perjalanan atau hilang, sikap anda...','Menyiapkannya jauh jauh hari agar tidak lupa.','Selalu membawa dokumen cadangan di tempat berbeda.','Menyimpan dengan sistem online agar bisa diakses dimana saja.','Menyimpan dokumen di dalam harddisk.','Tetap mempersiapkan seperti biasa yang anda lakukan.','Topik teknologi informasi dan komunikasi, mampu memanfaatkan teknologi untuk membantu pekerjaan dan memudahkan dalam menyelesaikan pekerjaan, penekanan disoal ada pada dokumen.',2,3,5,4,1),
    (34,1,'Anda merupakan seorang front office di sebuah perusahaan di instansi pemerintah. Tugas anda adalah melayani setiap tamu yang datang ke instansi pemerintah tempat anda mengabdi. Suatu hari anda kedatangan seorang tamu dan ingin bertemu dengan pimpinan anda untuk suatu urusan yang harus diputuskan pada saat itu juga. Sedangkan pimpinan anda baru saja pagi tadi harus keluar kota untuk urusan lain yang juga tidak bisa ditinggalkannya. Tamu tersebut terus mendesak anda untuk mencoba menghubungi atasan anda tapi setelah beberapa kali anda coba, nomer atasan anda tetap tidak dapat dihubungi, kemudian tamu tersebut meminta anda memberikan keputusan sikap anda...','Mengambil keputusan tanpa petunjuk atasan selama tidak bertentangan dengan kebijakan yang ada diperusahaan.','Tidak berani mengambil keputusan tanpa petunjuk atasan saya, dan meminta tamu tersebut datang besok.','Ragu - ragu dalam mengambil keputusan tanpa petunjuk atasan saya, karena takut melakukan kesalahan.','Menunda - nunda pengambilan keputusan tanpa petunjuk atasan saya karena takut melakukan kesalahan.','Mengambil keputusan tanpa petunjuk atasan karena sangat mendesak atasan pasti memakluminya asal benar.','Topik kemampuan mengendalikan diri, membuat keputusan yang tepat yang dapat diyakini kebenarannya, dengan berpedoman kepada prosedur, aturan (sop) yang ada selagi tidak menyalahi kebijakan perusahaan.',5,3,2,1,4),
    (35,1,'Karena kekurangan sumber daya manusia di sebuah kantor cabang perusahaan tempat anda bekerja, Atasan anda memutuskan hendak memindahkan anda ke cabang yang sama sekali tidak pernah anda kunjungi disebuah pulau terpencil, padahal anda adalah karyawan yang sudah lama mengabdi dan berprestasi dan anda cukup dekat dengan atasan, sikap anda...','Menolak dengan halus dan mengusulkan yang lain saja, Karena anda merupakan karyawan lama yang seharusnya tetap bekerja di kantor pusat.','Berdiskusi dengan atasan anda terkait proses pemindahan anda ke kantor cabang yang baru tersebut.','Bersedia di pindah tanpa membantah sedikit pun perintah dari atasan dan kebijakan perusahaan.','Menerima tapi berusaha mengusulkan karyawan yang lain saja karna anda merasa senior dan disegani di kantor.','Berangkat mengikuti keputusan perusahaan tentang pemindahan anda ke kantor cabang baru tersebut.','Topik integritas diri, tanggung jawab dan loyalitas terhadap pekerjaan dan harus bersifat terbuka dan jujur dengan keadaan sebenarnya, mengetahui proses, hak dan kewajiban anda, terkait hal tersebut anda dapat berdiskusi tentang pemindahan anda',1,5,4,2,3);

